version: "3.9"
services:
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    command: [ 'rodolpheche/wiremock', '--port 8080', '--verbose', '--record-mappings' ]
    volumes:
      - "./src/test/resources/mappings:/home/wiremock"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost", "||", "exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s
