browser:
browserVersion:
platform:
platformVersion:
device:
captureURL:
gridURL:
build:
appPath:
sauce:
browserStack:
jiraURL:
spiraURL:
resultVersion:
zapiCycleRegEx:
jqlQuery:
sutName:
sutVersion:
jiraResultFieldName:
jiraResultTransition:
maximise:
resolution:
