# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: frameworkium build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  THREAD_COUNT: 2
  CAPTURE_URL: http://capture-6c06138r.cloudapp.net
  SUT_NAME: frameworkium-bdd
  SUT_VERSION: $GITHUB_REF


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 1.8, 1.11 ]
    steps:
      - name: Notify Slack of CI start
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#frameworkium-ci'
        if: always()
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven - checkstyle
        run: mvn test-compile -B -U --show-version -DskipTests=true -Dmaven.javadoc.skip=true
      - name: Build with Maven - firefox off grid
        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=firefox -DreuseBrowser -Dheadless -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION" -Dwebdriver.firefox.logfile=/dev/null
      - name: Build with Maven - chrome on grid
        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=chrome -Dmaximise=True -DreuseBrowser=true -Dheadless=true -DgridURL=http://localhost:4444/wd/hub
      - name: Build with Maven - custom browser on grid
        run: mvn verify -B -Dthreads=$THREAD_COUNT -DcustomBrowserImpl=com.frameworkium.integration.CustomFirefoxImpl -Dmaximise=true  -DgridURL=http://localhost:4444/wd/hub -Dit.test=DocumentationTest 2> /dev/null
      - name: Build with Maven - test groups and verify that all @Before methods in BaseUITest
        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=chrome -Dgroups=fw-bugs -DreuseBrowser=true -Dheadless=true
        # Disabled until we have a JIRA to use
        #      - name: Build with Maven
        #        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=chrome -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION"
        # Disabled until we have saucelabs account
        #      - name: Build with Maven - saucelabs
        #        run: mvn verify -Dsauce=true -Dplatform=ios -Dbrowser=safari -DplatformVersion=8.0 -Ddevice=iPad -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION"
      - name: Build allure report
        if: always()
        run: mvn allure:report -B
      - name: Upload coverage Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true

      - name: Notify Slack of CI status
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#frameworkium-ci'
        if: always()


